### ISSUE TITLE
Add not-assigned counts

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/mg7#11]
In all the count files add an extra row with `Not assigned` values. 

- in the absolute counts files it will have the absolute number of the not assigned reads in that sample 
- in the frequency files it will have the frequency calculated dividing the number of the not assigned reads in that sample by the number of merged reads in that sample

**Comment by marina-manrique** [comment]
@laughedelic I have been discussing with @rtobes that for the time being we are not going to use this value (we would only need it for the general stats #9)  so we could close this

**Comment by laughedelic** [comment]
Ok. I'll leave it open, just move to the backlog.

**Comment by laughedelic** [comment]
As discussed yesterday, this value is useless, because all things that we will have in the reference DB have a mapping to TaxID. Also, it is partially done in 0529f0b17b5308914a223d3c548442a7cf6a2eab.
