### ISSUE TITLE
Specify test input data

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#115]
We need a definitive specification of test input data, both Illumina and PacBio. I'm going to arrange a meeting for this.

**Comment by marina-manrique** [comment]
👍

**Comment by marina-manrique** [comment]
@eparejatobes @rtobes 

here you can see the Illumina data we have for the mock communities

https://github.com/ohnosequences/mg7/pull/104#issuecomment-240657111

and here the list of organisms of each mock community https://github.com/ohnosequences/mg7/blob/91401e1e26dcea498d7f28bb39ecf7daa4eff40f/src/test/scala/mg7/testData.scala#L37

There are 2 communities (one with even concentration and the other one staggered) and we have 3 replicas per community (6 datasets in total). In my opinion it would be good to analyse everything to know how MG7 handles replicas although we pick later on only one dataset per community for the release testing, WDYT?

**Comment by rtobes** [comment]
I agree

**Comment by marina-manrique** [comment]
I discussed this with @eparejatobes as well and he agrees on running all the samples.

**Comment by laughedelic** [comment]
I'd like to see this with @marina-manrique and/or @eparejatobes (next week?). I'm not sure how `testData` is supposed to be used.

**Comment by marina-manrique** [comment]
Sure, what about next Monday morning?

**Comment by laughedelic** [comment]
OK

**Comment by marina-manrique** [comment]
@laughedelic @eparejatobes at 11 am at the coworking space?

**Comment by laughedelic** [comment]
@marina-manrique I just remembered that I arranged a meeting with Manuel on Monday morning 😓 sorry!! Can we shift this meeting later on Monday or Tuesday?

**Comment by laughedelic** [comment]
Meetings summary:

- the code in `testData.scala` describes expected ratios of the organisms in the mock-communities used for testing (see the samples mapping in https://github.com/ohnosequences/mg7/pull/104#issuecomment-240657111)
- these rates differ by orders of magnitude. The ones with rate 1 will determine the variance of the real values (obtained from the test run results) and this variance will be used to check that the other rates (x10, x100, ...)
- we are not automating this test now, but will do it in future
