### ISSUE TITLE
Preprocessing of Mock communities reads 

### ISSUE THREAD

**Issue by marina-manrique** [ohnosequences/mg7#116]
@eparejatobes @rtobes is it fine for you to run this reads preprocessing?

`trim_galore --quality 20 --fastqc --output_dir outputDir --paired reads1GZ reads2GZ`

from the user manual  `--quality`

> Trim low-quality ends from reads in addition to adapter removal.

**Comment by rtobes** [comment]
OK

**Comment by marina-manrique** [comment]
The preprocessed reads are ready `s3://resources.ohnosequences.com/ohnosequences/mg7/mock-communities-data/illumina/`

**Comment by laughedelic** [comment]
Is it done?

**Comment by marina-manrique** [comment]
yep, here `s3://resources.ohnosequences.com/ohnosequences/mg7/mock-communities-data/illumina/`

**Comment by laughedelic** [comment]
OK, I'm closing this then
