### ISSUE TITLE
Planning releases

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/mg7#13]
I intent to organize the requests from the [improvements list](https://github.com/era7bio/mg7-test/blob/mg7/urgent/improvements/docs/mg7-improvements.md). Probably I forgot something.

Here is the summary of the [milestones](https://github.com/ohnosequences/mg7/milestones):

* [v1.0-M1](https://github.com/ohnosequences/mg7/milestones/v1.0-M1)
  - See [release notes](https://github.com/ohnosequences/mg7/releases/tag/v1.0.0-M1)

* [v1.0-M2](https://github.com/ohnosequences/mg7/milestones/v1.0-M2)
  - See [release notes](https://github.com/ohnosequences/mg7/releases/tag/v1.0.0-M2)

----

* [v1.0-M3](https://github.com/ohnosequences/mg7/milestones/v1.0-M3)
* [v1.0-M4](https://github.com/ohnosequences/mg7/milestones/v1.0-M4)

@rtobes @marina-manrique @eparejatobes 
Please, review this

There is also a fancy summary board for the overview: https://waffle.io/ohnosequences/mg7

**Comment by laughedelic** [comment]
There is also issue #5, which needs some discussion.

**Comment by laughedelic** [comment]
I've shifted milestones:

- `M3 -> M4`
- `M2 -> M3`
- added new M2 for the changes needed by Monday (for running on the project)

**Comment by marina-manrique** [comment]
@laughedelic thanks for planning this, looks perfect to me. Just one thing, if it is not very hard I would move this
#11: Add not-assigned counts
to M3

**Comment by laughedelic** [comment]
@marina-manrique ok, let's it to M3, but at the moment I don't know how hard it is..

**Comment by laughedelic** [comment]
[v1.0.0-M2](https://github.com/ohnosequences/mg7/releases/tag/v1.0.0-M2) is released.

**Comment by laughedelic** [comment]
I'm closing this issue. I'm using milestones for planning releases.

See the [waffle board](https://waffle.io/ohnosequences/mg7) for the progress overview.

**Comment by eparejatobes** [comment]
that thing looks pretty good :+1:

**Comment by marina-manrique** [comment]
yep! love it !
