### ISSUE TITLE
Configurable Blast results filtering

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/mg7#38]
This is needed for Pacbio case. 

Probably it should be added to the Blast step.

**Comment by eparejatobes** [comment]
The idea is to add to the configuration parameters a predicate on the BLAST output record values.

**Comment by laughedelic** [comment]
meeting notes:

- 99% identity (`eerc_identity`)
- output fields should contain `qcovs` (query coverage for subject)
- keeping only those for whom this is 100%
- `max_target_seqs` should be set to maximum/default
- high `evalue`
- filtering by a configurable predicate should be added to the merge step
- filtering of result by `qcovs` is useful in general

**Comment by eparejatobes** [comment]
- `qcovs` should be always an output field; same about `pident`.
- `max_target_seqs` should be as big as possible

**Comment by laughedelic** [comment]
Actually, I think this is done in #49. I made the filtering predicate configurable, and added the mentioned defaults in #51. Is there anything missing here?

**Comment by eparejatobes** [comment]
Fine for me

**Comment by laughedelic** [comment]
Leaving this open, due to the changes in #52: the predicate is not configurable for now (it caused problems).

**Comment by laughedelic** [comment]
In the end it's fixed in #52. Closing this.
