### ISSUE TITLE
NoFlashDataflow lacks summary and stats

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#63]

**Comment by laughedelic** [comment]
At this moment it's by design. Because then you need to have another `stats` loquat for the `NoFlashDataflow`, because it has less inputs.

**Comment by eparejatobes** [comment]
I didn't quite inderstand your reply. Is it, for some reason, not possible to have stats for `NoFlashDataflow`?

**Comment by laughedelic** [comment]
Well, it is, but the code for collecting stats is not flexible: it requires as inputs some outputs from the flash-step. Loquat doesn't have "optional inputs", so you can have another `stats` and `summary` steps for this type of pipeline with a lot of code duplication, but I would prefer to make it somehow better.

**Comment by eparejatobes** [comment]
One way or another, this should be part of the no-flash option.

**Comment by laughedelic** [comment]
Not arguing with this. It just wasn't planned for the next release as not urgent feature that can wait until issues causing this difficulty get resolved.

**Comment by eparejatobes** [comment]
Note to self: needs discussion with @rtobes @marina-manrique

**Comment by laughedelic** [comment]
I think we have discussed this and decided to move stats/summary to a separate project. @eparejatobes Is this correct?

**Comment by eparejatobes** [comment]
Yes.

**Comment by laughedelic** [comment]
Ok. The I'm closing this.
