### ISSUE TITLE
Awesome MG7

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/mg7#67]
Once we're on `-RC1`, I want to add this project to the [awesome-pipeline](https://github.com/pditommaso/awesome-pipeline) list which I just encountered.
If anybody knows any other similar places where MG7 could be promoted, suggestions are welcome!

**Comment by eparejatobes** [comment]
Doesn't look really related with MG7.

**Comment by laughedelic** [comment]
```
grep bio
```

* [Antha](https://www.antha-lang.org/) - High-level language for biology.
* [Bpipe](https://github.com/ssadedin/bpipe/) - Tool for running and managing bioinformatics pipelines.
* [Cluster Flow](http://clusterflow.io) - Command-line tool which uses common cluster managers to run bioinformatics pipelines.
* [Loom](https://github.com/StanfordBioinformatics/loom) - Tool for running bioinformatics workflows locally or in the cloud.
* [Longbow](http://www.hecbiosim.ac.uk/longbow) - Job proxying tool for biomolecular simulations.
* [Moa](https://github.com/mfiers/Moa) - Lightweight workflows in bioinformatics.
* [Nextflow](http://www.nextflow.io) - Flow-based computational toolkit for reproducibile and scalable bioinformatics pipelines.
* [PipEngine](https://github.com/fstrozzi/bioruby-pipengine) Ruby based launcher for complex biological pipelines.
* [Rubra](https://github.com/bjpop/rubra) - Pipeline system for bioinformatics workflows.
* [SciLuigi](https://github.com/pharmbio/sciluigi) - Helper library for writing flexible scientific workflows in Luigi.
* [Snakemake](https://bitbucket.org/johanneskoester/snakemake/wiki/Home) - Tool for running and managing bioinformatics pipelines.
* [Biokepler](http://www.biokepler.org) - Bioinformatics Scientific Workflow for Distributed Analysis of Large-Scale Biological Data.
* [Galaxy](https://usegalaxy.org) - Web-based platform for biomedical research.
