### ISSUE TITLE
Rename best BLAST hit

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#85]
It is (at least for me) downright misleading as to what this actually is. Why not something like most specific?

@rtobes @marina-manrique

**Comment by rtobes** [comment]
BBHRT (Best BLAST Hit representative taxon)

or

BST (Best Score representative taxon)

**Comment by marina-manrique** [comment]
MST (Most Similar Taxon) ? 

Do you know if there is any standard name for this? maybe from Megan Mothur packages??

**Comment by rtobes** [comment]
Finally I think that it is better to maintain the acronym BBH because is extensively used with a flexible meaning

**Comment by eparejatobes** [comment]
Reopening, voting for MSA (Most Specific Assignment)
