### ISSUE TITLE
Replace "metagenomics" by "microbiome"?

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#87]
@marina-manrique suggests that in #82. Thoughts?

**Comment by marina-manrique** [comment]
it seems `16S metagenomics` is no longer accepted and metagenomics is now only applied to shotgun analysis, so we should be careful here distinguishing where we want to talk about microbiome analysis which is more general and might be 16S analysis or shotgun metagenomics or where we want to talk about taxonomy profiling/16S analysis

what do you all think?

**Comment by rtobes** [comment]
Yes, I thought to review the final version in that sense but in my opinion always is correct to talk about metagenomics samples, for 16S amplicon sequencing and for shotgun metagenomics sequencing.

We will review the final version.
