### ISSUE TITLE
add a description of the test datasets

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#90]
- [ ] which kind of data, community composition, etc
- [ ] minimal discussion of the results: accuracy, time, ...
- [ ] Explain how this is part of the release process

**Comment by marina-manrique** [comment]
We have to include as well the reference to the datasets themselves (SRA ERX IDs)

**Comment by laughedelic** [comment]
who's assigned?

**Comment by marina-manrique** [comment]
Me, I guess. I'm working on this tomorrow morning
